export const DEFAULT_FORMAT = 'markdown'
export const DEFAULT_HOST = 'mjj'
export const DEFAULT_PROXY = 'wsrv.nl'
const ENABLE_MOCK_HOST = false
export const CONFIG: Record<string, any> = {
  // Examples: local preview page and common sites; add/remove as needed
  localhost: {
    enabled: true,
    pasteEnabled: true,
    dragAndDropEnabled: true,
    format: 'markdown',
    host: 'imgur',
    proxy: 'none',
    buttons: [{ selector: 'textarea', position: 'after', text: '插入图片' }],
  },
  'v2ex.com': {
    enabled: true,
    pasteEnabled: true,
    dragAndDropEnabled: true,
    format: 'link',
    host: 'imgur',
    proxy: 'none',
    buttons: [
      {
        selector: '#reply-box > div.cell.flex-one-row > div:nth-child(1)',
        position: 'inside',
        text: '<a style="padding-left: 10px;"> + 插入图片</a>',
      },
      {
        selector: '#tab-preview',
        position: 'after',
        text: '<a class="tab-alt"> + 插入图片</a>',
      },
      {
        selector: 'button[onclick^="previewTopicContent"]',
        position: 'before',
        text: `<button type="button" class="super normal button" style="margin-right: 12px;"><li class="fa fa-plus"></li> &nbsp;插入图片</button>`,
      },
    ],
  },
  'greasyfork.org': {
    enabled: true,
    pasteEnabled: true,
    dragAndDropEnabled: true,
    format: 'markdown',
    buttons: [
      {
        selector: '.comment-screenshot-control',
        position: 'before',
      },
    ],
  },
  'nodeseek.com': {
    enabled: true,
    pasteEnabled: true,
    dragAndDropEnabled: true,
    format: 'markdown',
    buttons: [
      {
        selector: '#editor-body > div.mde-toolbar > .toolbar-item:last-of-type',
        position: 'after',
        text: '插入图片',
      },
    ],
  },
  'deepflood.com': {
    enabled: true,
    pasteEnabled: true,
    dragAndDropEnabled: true,
    format: 'markdown',
    buttons: [
      {
        selector: '#editor-body > div.mde-toolbar > .toolbar-item:last-of-type',
        position: 'after',
        text: '插入图片',
      },
    ],
  },
  '2libra.com': {
    enabled: true,
    pasteEnabled: true,
    dragAndDropEnabled: true,
    format: 'markdown',
    buttons: [
      {
        selector:
          '.w-md-editor > div.w-md-editor-toolbar > ul:nth-child(1) > li:last-of-type',
        position: 'after',
        text: '插入图片',
      },
    ],
  },
  'meta.appinn.net': {
    enabled: true,
    pasteEnabled: false,
    dragAndDropEnabled: false,
    format: 'markdown',
    host: 'appinn',
    proxy: 'none',
    buttons: [
      {
        selector: '.toolbar__button.upload',
        position: 'after',
        text: `<button class="btn no-text btn-icon toolbar__button upload-extended" tabindex="-1" title="上传" type="button" style="display: inline-flex; color: orangered;">
<svg class="fa d-icon d-icon-far-image svg-icon svg-string" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"><use href="#far-image"></use></svg>      <span aria-hidden="true"></span>
    </button>`,
      },
    ],
  },
  'github.com': {
    enabled: true,
    pasteEnabled: false,
    dragAndDropEnabled: false,
    format: 'markdown',
  },
}

export const I18N: Record<string, any> = {
  en: {
    header_title: 'Universal Image Uploader',
    btn_history: 'History',
    btn_settings: 'Settings',
    btn_close: 'Close',
    format_markdown: 'Markdown',
    format_html: 'HTML',
    format_bbcode: 'BBCode',
    format_link: 'Link',
    host_imgur: 'Imgur',
    host_tikolu: 'Tikolu',
    host_mjj: 'MJJ.Today',
    host_imgbb: 'ImgBB',
    host_appinn: 'Appinn',
    host_photo_lily: 'Photo.Lily',
    host_111666_best: '111666.best',
    host_skyimg: 'Skyimg',
    host_skyimg_webp: 'Skyimg (WebP)',
    host_stardots: 'StarDots',
    btn_select_images: 'Select images',
    progress_initial: 'Done 0/0',
    progress_done: 'Done {done}/{total}',
    hint_text:
      'Paste or drag images onto the page, or click Select to batch upload',
    settings_section_title: 'Settings',
    settings_site_buttons: 'Site Button Settings',
    placeholder_css_selector: 'CSS Selector',
    pos_before: 'Before',
    pos_after: 'After',
    pos_inside: 'Inside',
    placeholder_button_content: 'Button content (HTML allowed)',
    insert_image_button_default: 'Insert image',
    btn_save_and_insert: 'Save & Insert',
    btn_remove_button_temp: 'Remove button (temporary)',
    btn_clear_settings: 'Clear settings',
    drop_overlay: 'Release to upload images',
    log_uploading: 'Uploading: ',
    log_success: '✅ Success: ',
    log_failed: '❌ Failed: ',
    btn_copy: 'Copy',
    btn_open: 'Open',
    btn_delete: 'Delete',
    btn_edit: 'Edit',
    btn_update: 'Update',
    btn_cancel: 'Cancel',
    menu_open_panel: 'Open upload panel',
    menu_select_images: 'Select images',
    menu_settings: 'Settings',
    menu_enable_site: 'Enable uploader for this site',
    menu_disable_site: 'Disable uploader for this site',
    toggle_paste_enabled: 'Enable paste upload',
    toggle_drag_enabled: 'Enable drag-and-drop upload',
    toggle_webp_enabled: 'Convert to WebP',
    formats_section_title: 'Custom Formats',
    placeholder_format_name: 'Format name',
    placeholder_format_template: 'Format template',
    example_format_template: 'Example: {name} - {link}',
    btn_add_format: 'Add format',
    formats_col_name: 'Name',
    formats_col_template: 'Format',
    formats_col_ops: 'Actions',
    history_upload_page_prefix: 'Upload page: ',
    history_upload_page: 'Upload page: {host}',
    btn_history_count: 'History ({count})',
    btn_clear_history: 'Clear',
    default_image_name: 'image',
    proxy_none: 'No proxy',
    proxy_wsrv_nl: 'wsrv.nl',
    proxy_duckduckgo: 'DuckDuckGo',
    proxy_wsrv_nl_duckduckgo: 'wsrv.nl -> DuckDuckGo',
    multi_host_none: 'Also upload to',
    error_network: 'Network error',
    error_upload_failed: 'Upload failed',
    placeholder_uploading: 'Uploading "{name}"...',
    placeholder_upload_failed: 'Upload failed: {name}',
    stardots_config_title: 'StarDots API Configration',
    stardots_key_title: 'API Key',
    stardots_key_placeholder: 'Please Enter API Key',
    stardots_secret_title: 'API Secret',
    stardots_secret_placeholder: 'Please Enter API Secret',
    stardots_bucket_title: 'Bucket',
    stardots_bucket_placeholder: 'Please Enter Bucket',
    stardots_save_title: 'Save',
    stardots_save_result_title: '✅ Saved',
    stardots_get_credentials_title: 'Get StarDots credentails',
    stardots_set_config_tips:
      'Please select StarDots and complete the configuration.',
  },
  'zh-CN': {
    header_title: '通用图片上传助手',
    btn_history: '历史',
    btn_settings: '设置',
    btn_close: '关闭',
    format_markdown: 'Markdown',
    format_html: 'HTML',
    format_bbcode: 'BBCode',
    format_link: '链接',
    host_imgur: 'Imgur',
    host_tikolu: 'Tikolu',
    host_mjj: 'MJJ.Today',
    host_imgbb: 'ImgBB',
    host_appinn: 'Appinn',
    host_photo_lily: 'Photo.Lily',
    host_111666_best: '111666.best',
    host_skyimg: 'Skyimg',
    host_skyimg_webp: 'Skyimg (WebP)',
    host_stardots: 'StarDots',
    btn_select_images: '选择图片',
    progress_initial: '完成 0/0',
    progress_done: '完成 {done}/{total}',
    hint_text: '支持粘贴图片、拖拽图片到页面或点击选择图片进行批量上传',
    settings_section_title: '设置',
    settings_site_buttons: '站点按钮设置',
    placeholder_css_selector: 'CSS 选择器',
    pos_before: '之前',
    pos_after: '之后',
    pos_inside: '里面',
    placeholder_button_content: '按钮内容（可为 HTML）',
    insert_image_button_default: '插入图片',
    btn_save_and_insert: '保存并插入',
    btn_remove_button_temp: '移除按钮（临时）',
    btn_clear_settings: '清空设置',
    drop_overlay: '释放以上传图片',
    log_uploading: '上传中：',
    log_success: '✅ 成功：',
    log_failed: '❌ 失败：',
    btn_copy: '复制',
    btn_open: '打开',
    btn_delete: '删除',
    btn_edit: '编辑',
    btn_update: '更新',
    btn_cancel: '取消',
    menu_open_panel: '打开图片上传面板',
    menu_select_images: '选择图片',
    menu_settings: '设置',
    menu_enable_site: '为此站点启用上传',
    menu_disable_site: '为此站点禁用上传',
    toggle_paste_enabled: '启用粘贴上传',
    toggle_drag_enabled: '启用拖拽上传',
    toggle_webp_enabled: '转为 WebP',
    formats_section_title: '自定义格式',
    placeholder_format_name: '格式名称',
    placeholder_format_template: '格式内容',
    example_format_template: '示例：{name} - {link}',
    btn_add_format: '添加格式',
    formats_col_name: '名字',
    formats_col_template: '格式',
    formats_col_ops: '操作',
    history_upload_page_prefix: '上传页面：',
    history_upload_page: '上传页面：{host}',
    btn_history_count: '历史（{count}）',
    btn_clear_history: '清空',
    default_image_name: '图片',
    proxy_none: '无代理',
    proxy_wsrv_nl: 'wsrv.nl',
    proxy_duckduckgo: 'DuckDuckGo',
    proxy_wsrv_nl_duckduckgo: 'wsrv.nl → DuckDuckGo',
    multi_host_none: '同时上传至',
    error_network: '网络错误',
    error_upload_failed: '上传失败',
    placeholder_uploading: '正在上传「{name}」...',
    placeholder_upload_failed: '上传失败：{name}',
    stardots_config_title: 'StarDots API 配置',
    stardots_key_title: 'API Key',
    stardots_key_placeholder: '请输入 API Key',
    stardots_secret_title: 'API Secret',
    stardots_secret_placeholder: '请输入 API Secret',
    stardots_bucket_title: '存储桶',
    stardots_bucket_placeholder: '请输入 存储桶',
    stardots_save_title: '保存',
    stardots_save_result_title: '✅ 保存成功',
    stardots_get_credentials_title: '获取 StarDots 凭据',
    stardots_set_config_tips: '请选择 StarDots 并完成配置。',
  },
  'zh-TW': {
    header_title: '通用圖片上傳助手',
    btn_history: '歷史',
    btn_settings: '設定',
    btn_close: '關閉',
    format_markdown: 'Markdown',
    format_html: 'HTML',
    format_bbcode: 'BBCode',
    format_link: '連結',
    host_imgur: 'Imgur',
    host_tikolu: 'Tikolu',
    host_mjj: 'MJJ.Today',
    host_imgbb: 'ImgBB',
    host_appinn: 'Appinn',
    host_photo_lily: 'Photo.Lily',
    host_111666_best: '111666.best',
    host_skyimg: 'Skyimg',
    host_skyimg_webp: 'Skyimg (WebP)',
    host_stardots: 'StarDots',
    btn_select_images: '選擇圖片',
    progress_initial: '完成 0/0',
    progress_done: '完成 {done}/{total}',
    hint_text: '支援貼上、拖曳圖片到頁面或點擊選擇檔案進行批次上傳',
    settings_section_title: '設定',
    settings_site_buttons: '站點按鈕設定',
    placeholder_css_selector: 'CSS 選擇器',
    pos_before: '之前',
    pos_after: '之後',
    pos_inside: '裡面',
    placeholder_button_content: '按鈕內容（可為 HTML）',
    insert_image_button_default: '插入圖片',
    btn_save_and_insert: '保存並插入',
    btn_remove_button_temp: '移除按鈕（暫時）',
    btn_clear_settings: '清空設定',
    drop_overlay: '放開以上傳圖片',
    log_uploading: '上傳中：',
    log_success: '✅ 成功：',
    log_failed: '❌ 失敗：',
    btn_copy: '複製',
    btn_open: '打開',
    btn_delete: '刪除',
    btn_edit: '編輯',
    btn_update: '更新',
    btn_cancel: '取消',
    menu_open_panel: '打開圖片上傳面板',
    menu_select_images: '選擇圖片',
    menu_settings: '設定',
    menu_enable_site: '為此站點啟用上傳',
    menu_disable_site: '為此站點停用上傳',
    toggle_paste_enabled: '啟用貼上上傳',
    toggle_drag_enabled: '啟用拖曳上傳',
    toggle_webp_enabled: '轉為 WebP',
    formats_section_title: '自訂格式',
    placeholder_format_name: '格式名稱',
    placeholder_format_template: '格式內容',
    example_format_template: '範例：{name} - {link}',
    btn_add_format: '新增格式',
    formats_col_name: '名稱',
    formats_col_template: '格式',
    formats_col_ops: '操作',
    history_upload_page_prefix: '上傳頁面：',
    history_upload_page: '上傳頁面：{host}',
    btn_history_count: '歷史（{count}）',
    btn_clear_history: '清空',
    default_image_name: '圖片',
    proxy_none: '不使用代理',
    proxy_wsrv_nl: 'wsrv.nl',
    proxy_duckduckgo: 'DuckDuckGo',
    proxy_wsrv_nl_duckduckgo: 'wsrv.nl → DuckDuckGo',
    multi_host_none: '同時上傳至',
    error_network: '網路錯誤',
    error_upload_failed: '上傳失敗',
    placeholder_uploading: '正在上傳「{name}」...',
    placeholder_upload_failed: '上傳失敗：{name}',
    stardots_config_title: 'StarDots API 設定',
    stardots_key_title: 'API Key',
    stardots_key_placeholder: '請輸入 API Key',
    stardots_secret_title: 'API Secret',
    stardots_secret_placeholder: '請輸入 API Secret',
    stardots_bucket_title: '儲存桶',
    stardots_bucket_placeholder: '請輸入 儲存桶',
    stardots_save_title: '儲存',
    stardots_save_result_title: '✅ 儲存成功',
    stardots_get_credentials_title: '獲取 StarDots 憑據',
    stardots_set_config_tips: '請選擇 StarDots 並完成設定。',
  },
}

// Imgur Client ID pool (see upload-image.ts)
export const IMGUR_CLIENT_IDS = [
  '3107b9ef8b316f3',
  '442b04f26eefc8a',
  '59cfebe717c09e4',
  '60605aad4a62882',
  '6c65ab1d3f5452a',
  '83e123737849aa9',
  '9311f6be1c10160',
  'c4a4a563f698595',
  '81be04b9e4a08ce',
]

export const HISTORY_KEY = 'uiu_history'
export const FORMAT_MAP_KEY = 'uiu_format_map' // legacy
export const BTN_SETTINGS_MAP_KEY = 'uiu_site_btn_settings_map' // legacy
export const HOST_MAP_KEY = 'uiu_host_map' // legacy
export const PROXY_MAP_KEY = 'uiu_proxy_map' // legacy
export const SITE_SETTINGS_MAP_KEY = 'uiu_site_settings_map'
export const CUSTOM_FORMATS_KEY = 'uiu_custom_formats'
export const ALLOWED_FORMATS = ['markdown', 'html', 'bbcode', 'link']
export const ALLOWED_HOSTS = ENABLE_MOCK_HOST
  ? [
      'imgur',
      'tikolu',
      'mjj',
      'imgbb',
      'appinn',
      'skyimg',
      'skyimg_webp',
      'photo_lily',
      '111666_best',
      'mock',
      'mock2',
      'stardots',
    ]
  : [
      'imgur',
      'tikolu',
      'mjj',
      'imgbb',
      'appinn',
      'skyimg',
      'skyimg_webp',
      'photo_lily',
      '111666_best',
      'stardots',
    ]
export const ALLOWED_PROXIES = [
  'none',
  'wsrv.nl',
  'duckduckgo',
  'wsrv.nl-duckduckgo',
]
export const ALLOWED_PROXIES_MULTI_HOST = ['wsrv.nl', 'wsrv.nl-duckduckgo']
export const ALLOWED_BUTTON_POSITIONS = ['before', 'inside', 'after']
export const DEFAULT_BUTTON_POSITION = 'after'

export const APPINN_UPLOAD_ENDPOINT = 'https://h1.appinn.me/upload'
export const APPINN_UPLOAD_PARAMS = {
  authCode: 'appinn2',
  serverCompress: false,
  uploadChannel: 'telegram',
  uploadNameType: 'default',
  autoRetry: true,
}
